/** Auto-generated by scripts/sync-wc-attributes.mjs — do not edit manually */
export const wcAttributes = [
  {
    "id": 2,
    "name": "Boja",
    "slug": "pa_boja",
    "terms": [
      {
        "id": 141,
        "name": "Bela",
        "slug": "bela"
      },
      {
        "id": 142,
        "name": "Bela i Zlatna",
        "slug": "bela-i-zlatna"
      },
      {
        "id": 49,
        "name": "Crna",
        "slug": "crna"
      },
      {
        "id": 110,
        "name": "Crvena",
        "slug": "crvena"
      },
      {
        "id": 109,
        "name": "Ljubicasta",
        "slug": "ljubicasta"
      },
      {
        "id": 89,
        "name": "Matte Black",
        "slug": "matte-black-de"
      },
      {
        "id": 53,
        "name": "Plava",
        "slug": "plava"
      },
      {
        "id": 104,
        "name": "Roze",
        "slug": "roze"
      },
      {
        "id": 131,
        "name": "Tirkizna",
        "slug": "tirkizna"
      },
      {
        "id": 129,
        "name": "Titanium",
        "slug": "titanium"
      },
      {
        "id": 72,
        "name": "Zelena",
        "slug": "zelena"
      },
      {
        "id": 70,
        "name": "Zlatna",
        "slug": "zlatna"
      },
      {
        "id": 146,
        "name": "Zuta",
        "slug": "zuta"
      }
    ]
  },
  {
    "id": 9,
    "name": "Dimenzija trake (mm)",
    "slug": "pa_dimenzija-trake",
    "terms": [
      {
        "id": 568,
        "name": "100 X 610 mm",
        "slug": "100-x-610-mm"
      },
      {
        "id": 566,
        "name": "533 X 76 mm",
        "slug": "533-x-76-mm"
      }
    ]
  },
  {
    "id": 4,
    "name": "Energija udarca (J)",
    "slug": "pa_energija-udarca",
    "terms": [
      {
        "id": 501,
        "name": "1.8J",
        "slug": "1-8j"
      },
      {
        "id": 502,
        "name": "1.9J",
        "slug": "1-9j"
      },
      {
        "id": 503,
        "name": "2.1J",
        "slug": "2-1j"
      },
      {
        "id": 504,
        "name": "2.3J",
        "slug": "2-3j"
      },
      {
        "id": 505,
        "name": "2.4J",
        "slug": "2-4j"
      },
      {
        "id": 506,
        "name": "2.5J",
        "slug": "2-5j"
      },
      {
        "id": 507,
        "name": "2.6J",
        "slug": "2-6j"
      },
      {
        "id": 508,
        "name": "2.7J",
        "slug": "2-7j"
      },
      {
        "id": 500,
        "name": "2.8J",
        "slug": "2-8j"
      },
      {
        "id": 509,
        "name": "2.9J",
        "slug": "2-9j"
      },
      {
        "id": 499,
        "name": "2J",
        "slug": "2j"
      },
      {
        "id": 510,
        "name": "3J",
        "slug": "3j"
      }
    ]
  },
  {
    "id": 13,
    "name": "Kapacitet baterija (Ah)",
    "slug": "pa_kapacitet-baterija",
    "terms": [
      {
        "id": 630,
        "name": "1,3 Ah",
        "slug": "13-ah"
      },
      {
        "id": 635,
        "name": "1,4 Ah",
        "slug": "14-ah"
      },
      {
        "id": 637,
        "name": "1,5 Ah",
        "slug": "15-ah"
      },
      {
        "id": 642,
        "name": "1,6 Ah",
        "slug": "16-ah"
      },
      {
        "id": 631,
        "name": "12,0 Ah",
        "slug": "120-ah"
      },
      {
        "id": 643,
        "name": "2,0 Ah",
        "slug": "20-ah"
      },
      {
        "id": 911,
        "name": "2,5 Ah",
        "slug": "25-ah"
      },
      {
        "id": 638,
        "name": "3,0 Ah",
        "slug": "30-ah"
      },
      {
        "id": 669,
        "name": "4,0 Ah",
        "slug": "40-ah"
      },
      {
        "id": 677,
        "name": "5,0 Ah",
        "slug": "50-ah"
      },
      {
        "id": 680,
        "name": "6,0 Ah",
        "slug": "60-ah"
      }
    ]
  },
  {
    "id": 12,
    "name": "Konjska snaga (KS)",
    "slug": "pa_konjska-snaga",
    "terms": [
      {
        "id": 847,
        "name": "1,0 KS",
        "slug": "10-ks"
      },
      {
        "id": 892,
        "name": "1,6 KS",
        "slug": "16-ks"
      },
      {
        "id": 875,
        "name": "1,9 KS",
        "slug": "19-ks"
      },
      {
        "id": 856,
        "name": "11,0 KS",
        "slug": "110-ks"
      },
      {
        "id": 882,
        "name": "12,0 KS",
        "slug": "120-ks"
      },
      {
        "id": 842,
        "name": "13 KS",
        "slug": "13-ks"
      },
      {
        "id": 881,
        "name": "13,2 KS",
        "slug": "132-ks"
      },
      {
        "id": 872,
        "name": "15 KS",
        "slug": "15-ks"
      },
      {
        "id": 628,
        "name": "2,0 KS",
        "slug": "20-ks"
      },
      {
        "id": 866,
        "name": "2,3 KS",
        "slug": "23-ks"
      },
      {
        "id": 848,
        "name": "2,5 KS",
        "slug": "25-ks"
      },
      {
        "id": 886,
        "name": "2,7 KS",
        "slug": "27-ks"
      },
      {
        "id": 879,
        "name": "2,8 KS",
        "slug": "28-ks"
      },
      {
        "id": 849,
        "name": "3,0 KS",
        "slug": "30-ks"
      },
      {
        "id": 868,
        "name": "3,3 KS",
        "slug": "33-ks"
      },
      {
        "id": 869,
        "name": "3,9 KS",
        "slug": "39-ks"
      },
      {
        "id": 852,
        "name": "4,0 KS",
        "slug": "40-ks"
      },
      {
        "id": 843,
        "name": "5,0 KS",
        "slug": "50-ks"
      },
      {
        "id": 851,
        "name": "5,5 KS",
        "slug": "55-ks"
      },
      {
        "id": 853,
        "name": "6,0 KS",
        "slug": "60-ks"
      },
      {
        "id": 871,
        "name": "6,5 KS",
        "slug": "65-ks"
      },
      {
        "id": 854,
        "name": "7,0 KS",
        "slug": "70-ks"
      },
      {
        "id": 855,
        "name": "8,0 KS",
        "slug": "80-ks"
      }
    ]
  },
  {
    "id": 7,
    "name": "Potenciometar",
    "slug": "pa_potenciometar",
    "terms": []
  },
  {
    "id": 5,
    "name": "Prečnik lista (mm)",
    "slug": "pa_precnik-lista",
    "terms": [
      {
        "id": 518,
        "name": "115mm",
        "slug": "115-mm"
      },
      {
        "id": 519,
        "name": "125mm",
        "slug": "125-mm"
      },
      {
        "id": 520,
        "name": "150mm",
        "slug": "150-mm"
      },
      {
        "id": 580,
        "name": "165mm",
        "slug": "165mm"
      },
      {
        "id": 521,
        "name": "180mm",
        "slug": "180-mm"
      },
      {
        "id": 581,
        "name": "190mm",
        "slug": "190mm"
      },
      {
        "id": 522,
        "name": "200mm",
        "slug": "200-mm"
      },
      {
        "id": 523,
        "name": "230mm",
        "slug": "230-mm"
      },
      {
        "id": 549,
        "name": "260mm",
        "slug": "260mm"
      },
      {
        "id": 588,
        "name": "305mm",
        "slug": "305mm"
      },
      {
        "id": 575,
        "name": "315mm",
        "slug": "315mm"
      },
      {
        "id": 524,
        "name": "355mm",
        "slug": "355-mm"
      }
    ]
  },
  {
    "id": 11,
    "name": "Pritisak (bar)",
    "slug": "pa_pritisak",
    "terms": [
      {
        "id": 797,
        "name": "0.5-12 bara",
        "slug": "0-5-12-bara"
      },
      {
        "id": 808,
        "name": "1,5 bara",
        "slug": "15-bara"
      },
      {
        "id": 611,
        "name": "100 bari",
        "slug": "100-bari"
      },
      {
        "id": 613,
        "name": "110 bari",
        "slug": "110-bari"
      },
      {
        "id": 914,
        "name": "120 bari",
        "slug": "120-bari"
      },
      {
        "id": 915,
        "name": "125 bari",
        "slug": "125-bari"
      },
      {
        "id": 614,
        "name": "130 bari",
        "slug": "130-bari"
      },
      {
        "id": 916,
        "name": "135 bari",
        "slug": "135-bari"
      },
      {
        "id": 917,
        "name": "140 bari",
        "slug": "140-bari"
      },
      {
        "id": 920,
        "name": "15 bari",
        "slug": "15-bari"
      },
      {
        "id": 918,
        "name": "150 bari",
        "slug": "150-bari"
      },
      {
        "id": 919,
        "name": "160 bari",
        "slug": "160-bari"
      },
      {
        "id": 921,
        "name": "185 bari",
        "slug": "185-bari"
      },
      {
        "id": 800,
        "name": "2-10 bara",
        "slug": "2-10-bara"
      },
      {
        "id": 798,
        "name": "2-6 bara",
        "slug": "2-6-bara"
      },
      {
        "id": 922,
        "name": "2,0 bari",
        "slug": "20-bari"
      },
      {
        "id": 799,
        "name": "3-8 bara",
        "slug": "3-8-bara"
      },
      {
        "id": 791,
        "name": "3.5 bara",
        "slug": "3-5-bara"
      },
      {
        "id": 723,
        "name": "4,9-8,3 bar",
        "slug": "49-83-bar"
      },
      {
        "id": 792,
        "name": "4.5 bari",
        "slug": "4-5-bari"
      },
      {
        "id": 795,
        "name": "5-7 bara",
        "slug": "5-7-bara"
      },
      {
        "id": 796,
        "name": "5-8 bara",
        "slug": "5-8-bara"
      },
      {
        "id": 794,
        "name": "6 bara",
        "slug": "6-bara"
      },
      {
        "id": 790,
        "name": "6.2 bara",
        "slug": "6-2-bara"
      },
      {
        "id": 793,
        "name": "7 bara",
        "slug": "7-bara"
      }
    ]
  },
  {
    "id": 1,
    "name": "Proizvodjač",
    "slug": "pa_proizvodjac",
    "terms": [
      {
        "id": 1008,
        "name": "ABAC",
        "slug": "abac"
      },
      {
        "id": 1052,
        "name": "ADK",
        "slug": "adk"
      },
      {
        "id": 1071,
        "name": "AGM",
        "slug": "agm"
      },
      {
        "id": 1061,
        "name": "AGRINA",
        "slug": "agrina"
      },
      {
        "id": 1016,
        "name": "ALTUNA",
        "slug": "altuna"
      },
      {
        "id": 1014,
        "name": "ANTI FIRE",
        "slug": "anti-fire"
      },
      {
        "id": 1032,
        "name": "BENMAN",
        "slug": "benman"
      },
      {
        "id": 958,
        "name": "BIHUI",
        "slug": "bihui"
      },
      {
        "id": 1057,
        "name": "BLUE BIRD",
        "slug": "blue-bird"
      },
      {
        "id": 964,
        "name": "BorMann",
        "slug": "bormann"
      },
      {
        "id": 525,
        "name": "BOSCH",
        "slug": "bosch-professional"
      },
      {
        "id": 1072,
        "name": "CASTELGARDEN",
        "slug": "castelgarden"
      },
      {
        "id": 1066,
        "name": "CEDRUS",
        "slug": "cedrus"
      },
      {
        "id": 883,
        "name": "DAEWOO",
        "slug": "daewoo"
      },
      {
        "id": 1077,
        "name": "DAH Solar",
        "slug": "dah-solar"
      },
      {
        "id": 1078,
        "name": "DEDRA",
        "slug": "dedra"
      },
      {
        "id": 1041,
        "name": "DeWALT",
        "slug": "dewalt"
      },
      {
        "id": 1042,
        "name": "DIVINOL",
        "slug": "divinol"
      },
      {
        "id": 954,
        "name": "DOLOMITE",
        "slug": "dolomite"
      },
      {
        "id": 966,
        "name": "EINHELL",
        "slug": "einhell"
      },
      {
        "id": 1064,
        "name": "ELMARK",
        "slug": "elmark"
      },
      {
        "id": 938,
        "name": "ESAB",
        "slug": "esab"
      },
      {
        "id": 1047,
        "name": "EUROSTEP",
        "slug": "eurostep"
      },
      {
        "id": 1015,
        "name": "F.F.GROUP",
        "slug": "f-f-group"
      },
      {
        "id": 528,
        "name": "FERM",
        "slug": "ferm"
      },
      {
        "id": 950,
        "name": "Ford",
        "slug": "ford"
      },
      {
        "id": 527,
        "name": "GARDEN MASTER",
        "slug": "garden-master"
      },
      {
        "id": 1049,
        "name": "GETOUT",
        "slug": "getout"
      },
      {
        "id": 531,
        "name": "GRAPHITE",
        "slug": "graphite"
      },
      {
        "id": 1059,
        "name": "GRIFO",
        "slug": "grifo"
      },
      {
        "id": 1034,
        "name": "HARVEST",
        "slug": "harvest"
      },
      {
        "id": 1023,
        "name": "HEKA",
        "slug": "heka"
      },
      {
        "id": 960,
        "name": "HIKOKI",
        "slug": "hikoki"
      },
      {
        "id": 1048,
        "name": "HONDA",
        "slug": "honda"
      },
      {
        "id": 944,
        "name": "HUGONG",
        "slug": "hugong"
      },
      {
        "id": 813,
        "name": "HYUNDAI",
        "slug": "hyundai"
      },
      {
        "id": 942,
        "name": "INGCO - SUPER INGCO",
        "slug": "ingco"
      },
      {
        "id": 1027,
        "name": "ISKRA",
        "slug": "iskra"
      },
      {
        "id": 1031,
        "name": "KAPRO",
        "slug": "kapro"
      },
      {
        "id": 1069,
        "name": "KASEI",
        "slug": "kasei"
      },
      {
        "id": 1054,
        "name": "KASSMAYER",
        "slug": "kassmayer"
      },
      {
        "id": 1070,
        "name": "LONCIN",
        "slug": "loncin"
      },
      {
        "id": 1058,
        "name": "LYNX",
        "slug": "lynx"
      },
      {
        "id": 46,
        "name": "MAKITA",
        "slug": "makita"
      },
      {
        "id": 526,
        "name": "METABO",
        "slug": "metabo"
      },
      {
        "id": 956,
        "name": "MILWAUKEE",
        "slug": "milwaukee"
      },
      {
        "id": 965,
        "name": "NAKAYAMA",
        "slug": "nakayama"
      },
      {
        "id": 533,
        "name": "NEO",
        "slug": "neo"
      },
      {
        "id": 1030,
        "name": "OTC",
        "slug": "otc"
      },
      {
        "id": 1053,
        "name": "PANTHEROL",
        "slug": "pantherol"
      },
      {
        "id": 1028,
        "name": "PRAKTIK",
        "slug": "praktik"
      },
      {
        "id": 1005,
        "name": "PROSTO",
        "slug": "prosto"
      },
      {
        "id": 1043,
        "name": "PROXXON",
        "slug": "proxxon"
      },
      {
        "id": 1012,
        "name": "QBRICK",
        "slug": "qbrick"
      },
      {
        "id": 529,
        "name": "RAIDER",
        "slug": "raider"
      },
      {
        "id": 1051,
        "name": "reca",
        "slug": "reca"
      },
      {
        "id": 957,
        "name": "REM POWER",
        "slug": "rem-power"
      },
      {
        "id": 895,
        "name": "RIDGID",
        "slug": "ridgid"
      },
      {
        "id": 1060,
        "name": "Scheppach",
        "slug": "scheppach"
      },
      {
        "id": 1079,
        "name": "Shineray",
        "slug": "shineray"
      },
      {
        "id": 1073,
        "name": "ST-GARDEN",
        "slug": "st-garden"
      },
      {
        "id": 1039,
        "name": "SWORD",
        "slug": "sword"
      },
      {
        "id": 1003,
        "name": "TITAN",
        "slug": "titan"
      },
      {
        "id": 1046,
        "name": "TOPEX",
        "slug": "topex"
      },
      {
        "id": 1007,
        "name": "topmaster",
        "slug": "topmaster"
      },
      {
        "id": 1036,
        "name": "TRUPER",
        "slug": "truper"
      },
      {
        "id": 952,
        "name": "TYROLIT",
        "slug": "tyrolit"
      },
      {
        "id": 812,
        "name": "VARSTROJ",
        "slug": "varstroj"
      },
      {
        "id": 532,
        "name": "VERTO",
        "slug": "verto"
      },
      {
        "id": 1074,
        "name": "Villager",
        "slug": "villager"
      },
      {
        "id": 1045,
        "name": "WADFOW",
        "slug": "wadfow"
      },
      {
        "id": 1067,
        "name": "WEIBANG",
        "slug": "weibang"
      },
      {
        "id": 1068,
        "name": "WILLTEK",
        "slug": "willtek"
      },
      {
        "id": 959,
        "name": "WILO",
        "slug": "wilo"
      },
      {
        "id": 1065,
        "name": "WIRMAN",
        "slug": "wirman"
      }
    ]
  },
  {
    "id": 3,
    "name": "Snaga (W)",
    "slug": "pa_snaga",
    "terms": [
      {
        "id": 860,
        "name": "0,67 KW",
        "slug": "067-kw"
      },
      {
        "id": 821,
        "name": "0,8 KW",
        "slug": "08-kw"
      },
      {
        "id": 887,
        "name": "0,9 kW",
        "slug": "09-kw"
      },
      {
        "id": 780,
        "name": "1,1 kW",
        "slug": "11-kw"
      },
      {
        "id": 874,
        "name": "1,25 KW",
        "slug": "125-kw"
      },
      {
        "id": 877,
        "name": "1,3 KW",
        "slug": "13-kw"
      },
      {
        "id": 870,
        "name": "1,4 KW",
        "slug": "14-kw"
      },
      {
        "id": 781,
        "name": "1,5 kW",
        "slug": "15-kw"
      },
      {
        "id": 876,
        "name": "1,6 KW",
        "slug": "16-kw"
      },
      {
        "id": 785,
        "name": "1,7 kW",
        "slug": "17-kw"
      },
      {
        "id": 857,
        "name": "1,8 KW",
        "slug": "18-kw"
      },
      {
        "id": 878,
        "name": "1,85 KW",
        "slug": "185-kw"
      },
      {
        "id": 939,
        "name": "1.250 W",
        "slug": "1-250-w"
      },
      {
        "id": 910,
        "name": "10,8 V",
        "slug": "108-v"
      },
      {
        "id": 901,
        "name": "100 W",
        "slug": "100-w"
      },
      {
        "id": 622,
        "name": "1000 W",
        "slug": "1000-w"
      },
      {
        "id": 229,
        "name": "1000kw",
        "slug": "1000kw"
      },
      {
        "id": 564,
        "name": "1010W",
        "slug": "1010w"
      },
      {
        "id": 578,
        "name": "1050W",
        "slug": "1050w"
      },
      {
        "id": 818,
        "name": "11 kW",
        "slug": "11-kw-2"
      },
      {
        "id": 598,
        "name": "1100W",
        "slug": "1100w"
      },
      {
        "id": 617,
        "name": "1150 W",
        "slug": "1150-w"
      },
      {
        "id": 624,
        "name": "12 V",
        "slug": "12-v"
      },
      {
        "id": 586,
        "name": "1200V",
        "slug": "1200v"
      },
      {
        "id": 567,
        "name": "1200W",
        "slug": "1200w"
      },
      {
        "id": 884,
        "name": "1250 V",
        "slug": "1250-v"
      },
      {
        "id": 583,
        "name": "1300W",
        "slug": "1300w"
      },
      {
        "id": 888,
        "name": "135 W",
        "slug": "135-w"
      },
      {
        "id": 740,
        "name": "1350W",
        "slug": "1350w"
      },
      {
        "id": 907,
        "name": "1380 W",
        "slug": "1380-w"
      },
      {
        "id": 634,
        "name": "14,4 V",
        "slug": "144-v"
      },
      {
        "id": 543,
        "name": "1400W",
        "slug": "1400w"
      },
      {
        "id": 592,
        "name": "1430W",
        "slug": "1430w"
      },
      {
        "id": 735,
        "name": "15 Nm",
        "slug": "15-nm"
      },
      {
        "id": 894,
        "name": "150 W",
        "slug": "150-w"
      },
      {
        "id": 715,
        "name": "1500W",
        "slug": "1500w"
      },
      {
        "id": 713,
        "name": "1510W",
        "slug": "1510w"
      },
      {
        "id": 741,
        "name": "1550W",
        "slug": "1550w"
      },
      {
        "id": 829,
        "name": "160 W",
        "slug": "160-w"
      },
      {
        "id": 606,
        "name": "1600W",
        "slug": "1600w"
      },
      {
        "id": 548,
        "name": "1650W",
        "slug": "1650w"
      },
      {
        "id": 612,
        "name": "1700W",
        "slug": "1700w"
      },
      {
        "id": 730,
        "name": "18 J",
        "slug": "18-j"
      },
      {
        "id": 636,
        "name": "18 V",
        "slug": "18-v"
      },
      {
        "id": 604,
        "name": "1800W",
        "slug": "1800w"
      },
      {
        "id": 558,
        "name": "180W",
        "slug": "180w"
      },
      {
        "id": 777,
        "name": "1900W",
        "slug": "1900w"
      },
      {
        "id": 556,
        "name": "190W",
        "slug": "190w"
      },
      {
        "id": 817,
        "name": "1kW",
        "slug": "1kw"
      },
      {
        "id": 838,
        "name": "2 KW",
        "slug": "2-kw"
      },
      {
        "id": 867,
        "name": "2,1 KW",
        "slug": "21-kw"
      },
      {
        "id": 787,
        "name": "2,2 kW",
        "slug": "22-kw"
      },
      {
        "id": 734,
        "name": "2,3 J",
        "slug": "23-j"
      },
      {
        "id": 832,
        "name": "2,8 kW",
        "slug": "28-kw"
      },
      {
        "id": 940,
        "name": "2.2 KW",
        "slug": "2-2-kw"
      },
      {
        "id": 824,
        "name": "20 V",
        "slug": "20-v"
      },
      {
        "id": 574,
        "name": "2000W",
        "slug": "2000w"
      },
      {
        "id": 746,
        "name": "200W",
        "slug": "200w"
      },
      {
        "id": 599,
        "name": "2100W",
        "slug": "2100w"
      },
      {
        "id": 756,
        "name": "210W",
        "slug": "210w"
      },
      {
        "id": 900,
        "name": "220 W",
        "slug": "220-w"
      },
      {
        "id": 550,
        "name": "2200W",
        "slug": "2200w"
      },
      {
        "id": 828,
        "name": "230 V",
        "slug": "230-v"
      },
      {
        "id": 744,
        "name": "2300W",
        "slug": "2300w"
      },
      {
        "id": 546,
        "name": "230mm",
        "slug": "230mm"
      },
      {
        "id": 610,
        "name": "230W",
        "slug": "230w"
      },
      {
        "id": 825,
        "name": "2350W",
        "slug": "2350w"
      },
      {
        "id": 703,
        "name": "2400W",
        "slug": "2400w"
      },
      {
        "id": 554,
        "name": "240W",
        "slug": "240w"
      },
      {
        "id": 827,
        "name": "2500 W",
        "slug": "2500-w"
      },
      {
        "id": 721,
        "name": "250W",
        "slug": "250w"
      },
      {
        "id": 706,
        "name": "2600W",
        "slug": "2600w"
      },
      {
        "id": 831,
        "name": "280 W",
        "slug": "280-w"
      },
      {
        "id": 889,
        "name": "2800 W",
        "slug": "2800-w"
      },
      {
        "id": 815,
        "name": "2kW",
        "slug": "2kw"
      },
      {
        "id": 814,
        "name": "3 kW",
        "slug": "3-kw"
      },
      {
        "id": 820,
        "name": "3,0 KW",
        "slug": "30-kw"
      },
      {
        "id": 736,
        "name": "3,1 J",
        "slug": "31-j"
      },
      {
        "id": 732,
        "name": "3,2 J",
        "slug": "32-j"
      },
      {
        "id": 733,
        "name": "3,4 J",
        "slug": "34-j"
      },
      {
        "id": 641,
        "name": "3,6 V",
        "slug": "36-v"
      },
      {
        "id": 845,
        "name": "3000 W",
        "slug": "3000-w"
      },
      {
        "id": 560,
        "name": "300W",
        "slug": "300w"
      },
      {
        "id": 767,
        "name": "3100W",
        "slug": "3100w"
      },
      {
        "id": 562,
        "name": "310W",
        "slug": "310w"
      },
      {
        "id": 725,
        "name": "320W",
        "slug": "320w"
      },
      {
        "id": 709,
        "name": "330W",
        "slug": "330w"
      },
      {
        "id": 897,
        "name": "340 W",
        "slug": "340-w"
      },
      {
        "id": 748,
        "name": "350W",
        "slug": "350w"
      },
      {
        "id": 681,
        "name": "36 V",
        "slug": "36-v-2"
      },
      {
        "id": 698,
        "name": "370W",
        "slug": "370w"
      },
      {
        "id": 718,
        "name": "380W",
        "slug": "380w"
      },
      {
        "id": 864,
        "name": "4,0 KW",
        "slug": "40-kw"
      },
      {
        "id": 880,
        "name": "4,8 KW",
        "slug": "48-kw"
      },
      {
        "id": 834,
        "name": "40 V",
        "slug": "40-v"
      },
      {
        "id": 551,
        "name": "400",
        "slug": "400"
      },
      {
        "id": 552,
        "name": "400W",
        "slug": "400w"
      },
      {
        "id": 924,
        "name": "410 W",
        "slug": "410-w"
      },
      {
        "id": 912,
        "name": "420 W",
        "slug": "420-w"
      },
      {
        "id": 830,
        "name": "430 W",
        "slug": "430-w"
      }
    ]
  },
  {
    "id": 6,
    "name": "Težina",
    "slug": "pa_tezina",
    "terms": [
      {
        "id": 776,
        "name": "0,25 kg",
        "slug": "025-kg"
      },
      {
        "id": 607,
        "name": "0,56",
        "slug": "056"
      },
      {
        "id": 608,
        "name": "0,57kg",
        "slug": "057kg"
      },
      {
        "id": 774,
        "name": "0,6 kg",
        "slug": "06-kg"
      },
      {
        "id": 609,
        "name": "0,71kg",
        "slug": "071kg"
      },
      {
        "id": 696,
        "name": "0,8 kg",
        "slug": "08-kg"
      },
      {
        "id": 625,
        "name": "0,84 kg",
        "slug": "084-kg"
      },
      {
        "id": 775,
        "name": "0,9 kg",
        "slug": "09-kg"
      },
      {
        "id": 555,
        "name": "0,98kg",
        "slug": "098kg"
      },
      {
        "id": 699,
        "name": "1,0 kg",
        "slug": "10-kg"
      },
      {
        "id": 647,
        "name": "1,1 kg",
        "slug": "11-kg"
      },
      {
        "id": 779,
        "name": "1,12 kg",
        "slug": "112-kg"
      },
      {
        "id": 648,
        "name": "1,2 kg",
        "slug": "12-kg"
      },
      {
        "id": 644,
        "name": "1,3 kg",
        "slug": "13-kg"
      },
      {
        "id": 561,
        "name": "1,4kg",
        "slug": "14kg"
      },
      {
        "id": 596,
        "name": "1,5kg",
        "slug": "15kg"
      },
      {
        "id": 708,
        "name": "1,6 kg",
        "slug": "16-kg"
      },
      {
        "id": 557,
        "name": "1,6kg",
        "slug": "16kg"
      },
      {
        "id": 553,
        "name": "1,7kg",
        "slug": "17kg"
      },
      {
        "id": 649,
        "name": "1,8 kg",
        "slug": "18-kg"
      },
      {
        "id": 645,
        "name": "1,9 kg",
        "slug": "19-kg"
      },
      {
        "id": 539,
        "name": "1.8kg",
        "slug": "1-8kg"
      },
      {
        "id": 727,
        "name": "10,1 kg",
        "slug": "101-kg"
      },
      {
        "id": 804,
        "name": "10,6 kg",
        "slug": "106-kg"
      },
      {
        "id": 805,
        "name": "11,1 kg",
        "slug": "111-kg"
      },
      {
        "id": 806,
        "name": "11,5 kg",
        "slug": "115-kg"
      },
      {
        "id": 731,
        "name": "12,2 kg",
        "slug": "122-kg"
      },
      {
        "id": 591,
        "name": "12,6kg",
        "slug": "126kg"
      },
      {
        "id": 737,
        "name": "13 kg",
        "slug": "13-kg-2"
      },
      {
        "id": 665,
        "name": "13,5 kg",
        "slug": "135-kg"
      },
      {
        "id": 716,
        "name": "14,7 kg",
        "slug": "147-kg"
      },
      {
        "id": 750,
        "name": "14,9 kg",
        "slug": "149-kg"
      },
      {
        "id": 682,
        "name": "15 kg",
        "slug": "15-kg"
      },
      {
        "id": 751,
        "name": "15,2 kg",
        "slug": "152-kg"
      },
      {
        "id": 809,
        "name": "15,9 kg",
        "slug": "159-kg"
      },
      {
        "id": 773,
        "name": "16,0 kg",
        "slug": "160-kg"
      },
      {
        "id": 758,
        "name": "16,3 kg",
        "slug": "163-kg"
      },
      {
        "id": 752,
        "name": "16,6 kg",
        "slug": "166-kg"
      },
      {
        "id": 683,
        "name": "16,9 kg",
        "slug": "169-kg"
      },
      {
        "id": 760,
        "name": "17,0 kg",
        "slug": "170-kg"
      },
      {
        "id": 753,
        "name": "17,2 kg",
        "slug": "172-kg"
      },
      {
        "id": 685,
        "name": "17,5 kg",
        "slug": "175-kg"
      },
      {
        "id": 667,
        "name": "17,8 kg",
        "slug": "178-kg"
      },
      {
        "id": 684,
        "name": "18,0 kg",
        "slug": "180-kg"
      },
      {
        "id": 640,
        "name": "18,4 kg",
        "slug": "184-kg"
      },
      {
        "id": 618,
        "name": "18,5 kg",
        "slug": "185-kg"
      },
      {
        "id": 761,
        "name": "19,6 kg",
        "slug": "196-kg"
      },
      {
        "id": 722,
        "name": "19,8 kg",
        "slug": "198-kg"
      },
      {
        "id": 559,
        "name": "1kg",
        "slug": "1kg"
      },
      {
        "id": 616,
        "name": "2 kg",
        "slug": "2-kg"
      },
      {
        "id": 646,
        "name": "2,0 kg",
        "slug": "20-kg"
      },
      {
        "id": 659,
        "name": "2,1 kg",
        "slug": "21-kg"
      },
      {
        "id": 542,
        "name": "2,1kg",
        "slug": "21kg"
      },
      {
        "id": 545,
        "name": "2,2kg",
        "slug": "22kg"
      },
      {
        "id": 650,
        "name": "2,3 kg",
        "slug": "23-kg"
      },
      {
        "id": 563,
        "name": "2,4kg",
        "slug": "24kg"
      },
      {
        "id": 601,
        "name": "2,5kg",
        "slug": "25kg"
      },
      {
        "id": 544,
        "name": "2,6kg",
        "slug": "26kg"
      },
      {
        "id": 661,
        "name": "2,7 kg",
        "slug": "27-kg"
      },
      {
        "id": 620,
        "name": "2,8 kg",
        "slug": "28-kg"
      },
      {
        "id": 663,
        "name": "2,9 kg",
        "slug": "29-kg"
      },
      {
        "id": 593,
        "name": "20,6kg",
        "slug": "206kg"
      },
      {
        "id": 590,
        "name": "20,7kg",
        "slug": "207kg"
      },
      {
        "id": 762,
        "name": "22 kg",
        "slug": "22-kg"
      },
      {
        "id": 782,
        "name": "24 kg",
        "slug": "24-kg"
      },
      {
        "id": 807,
        "name": "25,1 kg",
        "slug": "251-kg"
      },
      {
        "id": 759,
        "name": "26,8 kg",
        "slug": "268-kg"
      },
      {
        "id": 763,
        "name": "27,2 kg",
        "slug": "272-kg"
      },
      {
        "id": 666,
        "name": "27,3 kg",
        "slug": "273-kg"
      },
      {
        "id": 686,
        "name": "27,6 kg",
        "slug": "276-kg"
      },
      {
        "id": 719,
        "name": "28,1 kg",
        "slug": "281-kg"
      },
      {
        "id": 764,
        "name": "28,5 kg",
        "slug": "285-kg"
      },
      {
        "id": 784,
        "name": "29,0 kg",
        "slug": "290-kg"
      },
      {
        "id": 714,
        "name": "29,5 kg",
        "slug": "295-kg"
      },
      {
        "id": 695,
        "name": "3,0 kg",
        "slug": "30-kg"
      },
      {
        "id": 651,
        "name": "3,1 kg",
        "slug": "31-kg"
      },
      {
        "id": 585,
        "name": "3,2kg",
        "slug": "32kg"
      },
      {
        "id": 587,
        "name": "3,3kg",
        "slug": "33kg"
      },
      {
        "id": 621,
        "name": "3,4 kg",
        "slug": "34-kg"
      },
      {
        "id": 573,
        "name": "3,4kg",
        "slug": "34kg"
      },
      {
        "id": 668,
        "name": "3,5 kg",
        "slug": "35-kg"
      },
      {
        "id": 673,
        "name": "3,6 kg",
        "slug": "36-kg"
      },
      {
        "id": 662,
        "name": "3,7 kg",
        "slug": "37-kg"
      },
      {
        "id": 582,
        "name": "3,8kg",
        "slug": "38kg"
      },
      {
        "id": 679,
        "name": "3,9 kg",
        "slug": "39-kg"
      },
      {
        "id": 786,
        "name": "30,0 kg",
        "slug": "300-kg"
      },
      {
        "id": 783,
        "name": "32 kg",
        "slug": "32-kg"
      },
      {
        "id": 771,
        "name": "32,5 kg",
        "slug": "325-kg"
      },
      {
        "id": 765,
        "name": "33,4 kg",
        "slug": "334-kg"
      },
      {
        "id": 754,
        "name": "33,8 kg",
        "slug": "338-kg"
      },
      {
        "id": 769,
        "name": "35 kg",
        "slug": "35-kg-2"
      },
      {
        "id": 687,
        "name": "39,8 kg",
        "slug": "398-kg"
      },
      {
        "id": 572,
        "name": "3kg",
        "slug": "3kg"
      },
      {
        "id": 676,
        "name": "4,0 kg",
        "slug": "40-kg"
      },
      {
        "id": 584,
        "name": "4,1kg",
        "slug": "41kg"
      },
      {
        "id": 570,
        "name": "4,2kg",
        "slug": "42kg"
      },
      {
        "id": 639,
        "name": "4,3 kg",
        "slug": "43-kg"
      },
      {
        "id": 565,
        "name": "4,3kg",
        "slug": "43kg"
      },
      {
        "id": 694,
        "name": "4,4 kg",
        "slug": "44-kg"
      },
      {
        "id": 654,
        "name": "4,5 kg",
        "slug": "45-kg"
      }
    ]
  },
  {
    "id": 14,
    "name": "Uvoznik",
    "slug": "pa_uvoznik",
    "terms": [
      {
        "id": 993,
        "name": "ABM d.o.o. - Prokuplje",
        "slug": "abm-doo"
      },
      {
        "id": 992,
        "name": "BB link d.o.o. - Beograd",
        "slug": "bb-link"
      },
      {
        "id": 991,
        "name": "Braytron Balkan d.o.o. - Novi Pazar",
        "slug": "braytron-balkan"
      },
      {
        "id": 1056,
        "name": "CIAK D.O.O. - Novi Sad",
        "slug": "ciak-d-o-o-novi-sad"
      },
      {
        "id": 1000,
        "name": "Ecomex doo - Čačak",
        "slug": "ecomex-doo"
      },
      {
        "id": 997,
        "name": "Einhell doo - Beograd",
        "slug": "einhell-doo"
      },
      {
        "id": 990,
        "name": "Elementa doo - Subotica",
        "slug": "elementa-doo"
      },
      {
        "id": 994,
        "name": "Elmax doo",
        "slug": "elmax-doo"
      },
      {
        "id": 996,
        "name": "Esterno Trade d.o.o. - Valjevo",
        "slug": "esterno-trade"
      },
      {
        "id": 995,
        "name": "ITH Trading doo - Beograd",
        "slug": "ith-trading-doo"
      },
      {
        "id": 1050,
        "name": "LACUNA d.o.o.",
        "slug": "lacuna-d-o-o"
      },
      {
        "id": 985,
        "name": "Metabo Centar d.o.o. - Kragujevac",
        "slug": "metabo-centar-doo"
      },
      {
        "id": 1024,
        "name": "Mipal d.o.o. - 11050 Beograd",
        "slug": "mipal-d-o-o-11050-beograd"
      },
      {
        "id": 983,
        "name": "NA DEKLARACIJI PROIZVODA",
        "slug": "na-deklaraciji-proizvoda"
      },
      {
        "id": 1040,
        "name": "Nexico d.o.o. - Beograd",
        "slug": "nexico-d-o-o-beograd"
      },
      {
        "id": 989,
        "name": "ODC d.o.o. - Zaječar",
        "slug": "odc-doo"
      },
      {
        "id": 1033,
        "name": "OLI-KOPP d.o.o. - 36210 Vrnjačka Banja",
        "slug": "oli-kopp-d-o-o-36210-vrnjacka-banja"
      },
      {
        "id": 988,
        "name": "Poljobit d.o.o. - Pančevo",
        "slug": "poljobit-doo"
      },
      {
        "id": 1035,
        "name": "Proizvedeno u Srbiji",
        "slug": "proizvedeno-u-srbiji"
      },
      {
        "id": 986,
        "name": "Robert Bosch d.o.o. - Beograd",
        "slug": "robert-bosch"
      },
      {
        "id": 999,
        "name": "Savacoop d.o.o. - Novi Sad",
        "slug": "savacoop-doo"
      },
      {
        "id": 1062,
        "name": "Simpeks d.o.o. - Markovac",
        "slug": "simpeks-d-o-o"
      },
      {
        "id": 1010,
        "name": "TEHNOGAMA d.o.o. - Beograd",
        "slug": "tehnogama-d-o-o-beograd"
      },
      {
        "id": 1063,
        "name": "Tool Experts d.o.o. - Beograd",
        "slug": "tool-experts-d-o-o-beograd"
      },
      {
        "id": 987,
        "name": "Varcom d.o.o. - Smederevo",
        "slug": "varcom-doo"
      },
      {
        "id": 984,
        "name": "Vermax d.o.o. - Beograd",
        "slug": "vermax-doo"
      },
      {
        "id": 998,
        "name": "WILO d.o.o. - Beograd",
        "slug": "gas-lider-doo"
      }
    ]
  },
  {
    "id": 15,
    "name": "Zemlja porekla",
    "slug": "pa_zemlja-porekla",
    "terms": [
      {
        "id": 1044,
        "name": "Austrija",
        "slug": "austrija"
      },
      {
        "id": 975,
        "name": "Belgija",
        "slug": "belgija"
      },
      {
        "id": 974,
        "name": "Bugarska",
        "slug": "bugarska"
      },
      {
        "id": 1021,
        "name": "Češka",
        "slug": "ceska"
      },
      {
        "id": 1026,
        "name": "Hong Kong",
        "slug": "hong-kong"
      },
      {
        "id": 1018,
        "name": "Indija",
        "slug": "indija"
      },
      {
        "id": 1009,
        "name": "ITALY",
        "slug": "italy"
      },
      {
        "id": 978,
        "name": "Japan",
        "slug": "japan"
      },
      {
        "id": 1020,
        "name": "Južna Koreja",
        "slug": "juzna-koreja"
      },
      {
        "id": 973,
        "name": "Kina",
        "slug": "kina"
      },
      {
        "id": 1011,
        "name": "Madjarska",
        "slug": "madjarska"
      },
      {
        "id": 1004,
        "name": "Malezija",
        "slug": "malezija"
      },
      {
        "id": 1029,
        "name": "Meksiko",
        "slug": "meksiko"
      },
      {
        "id": 1025,
        "name": "N/A",
        "slug": "n-a"
      },
      {
        "id": 977,
        "name": "Nemačka",
        "slug": "nemacka"
      },
      {
        "id": 1013,
        "name": "Poljska",
        "slug": "poljska"
      },
      {
        "id": 980,
        "name": "Rumunija",
        "slug": "rumunija"
      },
      {
        "id": 981,
        "name": "Rusija",
        "slug": "rusija"
      },
      {
        "id": 1006,
        "name": "SAD",
        "slug": "sad"
      },
      {
        "id": 1019,
        "name": "Slovačka",
        "slug": "slovacka"
      },
      {
        "id": 1017,
        "name": "Španija",
        "slug": "spanija"
      },
      {
        "id": 982,
        "name": "Srbija",
        "slug": "srbija"
      },
      {
        "id": 1037,
        "name": "Švajcarska",
        "slug": "svajcarska"
      },
      {
        "id": 1022,
        "name": "Tajland",
        "slug": "tajland"
      },
      {
        "id": 976,
        "name": "Tajvan",
        "slug": "tajvan"
      },
      {
        "id": 1038,
        "name": "Turska",
        "slug": "turska"
      },
      {
        "id": 979,
        "name": "Velika Britanija",
        "slug": "velika-britanija"
      }
    ]
  }
] as const;
